name: Build Windows EXE + Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller==6.10.0

      - name: PyInstaller (onedir, windowed)
        run: |
          pyinstaller ^
            --noconfirm ^
            --onedir ^
            --windowed ^
            --name "STB_PRO" ^
            --icon "stbpro.ico" ^
            --add-data "stbpro.ico;." ^
            app.py

      - name: Ensure dist content
        run: dir dist\STB_PRO

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build installer (Inno Setup)
        run: |
          iscc inno_installer.iss
        shell: cmd

      - name: Upload artifacts (app + installer)
        uses: actions/upload-artifact@v4
        with:
          name: STB_PRO-Windows
          path: |
            dist/STB_PRO/**
            STB_PRO-Setup.exe